### ISSUE TITLE
Invalid weight computation

### ISSUE THREAD

**Issue by rohjunha** [takoika/PrioritizedExperienceReplay#1]
First of all, thanks for making the code publicly available.
I realized that the weight is computed as
* (1./self.memory_size/priority)**-beta

However, according to the original paper, it should be
* (self.memory_size * priority)**-beta
* (1./self.memory_size/priority)**beta

Also, the weights should be normalized by the maximum weight
* weights = [weight / max(weights) for weight in weights]

**Comment by takoika** [comment]
Thank you for bringing it to my attention.
Your indication is exactly on target. I fixed two places on code.
